Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = "Plaksin Anton"
COLLABORATORS = ""

---

In [2]:
import numpy as np

from numpy.testing import assert_allclose


### Часть I. Постройте отражение Хаусхолдера для вектора.

Дан вектор $\mathbf{x}$ и плоскость, заданная вектором нормали $\mathbf{u}$. Преобразование Хаусхолдера отражает $\mathbf{x}$ относительно плоскости.

Матрица преобразований Хаусхолдера:
$$ \mathbf{H} = \mathbf{1} - 2 \mathbf{u} \mathbf{u}^T $$

Если даны два вектора $\mathbf{x}$ и $\mathbf{y}$ одинаковой длины, поворот, преобразующий $\mathbf{x}$ в $\mathbf{y}$ называется преобразованием Хаусхолдера с
$$ \mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{\left|\mathbf{x} - \mathbf{y}\right|} $$

Напишите функцию, преобразующую заданный вектор $\mathbf{x} = (x_1, \dots, x_n)$ в $\mathbf{y} = (\left|\mathbf{x}\right|, 0, \dots, 0)^T$, используя преобразование Хаусхолдера.


In [3]:
def householder(vec):
    """Создает отражение Хаусхолдера, преобразующее 2-ю, 3-ю и т.д. компоненты вектора vec в нули.
    
    Parameters
    ----------
    vec : array-like of floats, shape (n,)
        Введенный вектор
    
    Returns
    -------
    outvec : array of floats, shape (n,)
        Преобразованный вектор, причем ``outvec[1:]==0`` и ``|outvec| == |vec|``
    H : array of floats, shape (n, n)
        Ортогональная матрица отражений Хаусхолдера
    """

    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)

    if (np.size(vec) == 1) and (np.linalg.norm(vec)) < 1e-8:
      return([0],[[1]])

    x = vec
    y = np.zeros(np.size(vec))
    y[0] = np.linalg.norm(vec)
    U = (x - y) / np.linalg.norm(x - y)
    H = np.eye(np.size(vec)) - 2 * (U[np.newaxis, :].T @ U[np.newaxis, :] )
    return(y, H)

In [4]:
    V = np.array([1, 2, 3])
    V = np.asarray(V, dtype=float)
    if V.ndim != 1:
        raise ValueError("V.ndim = %s, expected 1" % V.ndim)

    x = V
    y = np.zeros(np.size(V))
    y[0] = np.linalg.norm(V)
    print(x - y)
    print(np.linalg.norm(x - y))
    u = (x - y) / np.linalg.norm(x - y)
    print(u)
    print(u[np.newaxis, :].T)
    print(u[np.newaxis, :].T @ u[np.newaxis, :])
    print(2 * (u[np.newaxis, :].T @ u[np.newaxis, :] ))
    print(1 - 2 * (u[np.newaxis, :].T @ u[np.newaxis, :]))
    H = np.eye(3) - 2 * (u[np.newaxis, :].T @ u[np.newaxis, :])
    print(H)
    print(H @ x)

[-2.74165739  2.          3.        ]
4.529534769317056
[-0.60528454  0.44154645  0.66231968]
[[-0.60528454]
 [ 0.44154645]
 [ 0.66231968]]
[[ 0.36636938 -0.26726124 -0.40089186]
 [-0.26726124  0.19496327  0.2924449 ]
 [-0.40089186  0.2924449   0.43866735]]
[[ 0.73273876 -0.53452248 -0.80178373]
 [-0.53452248  0.38992654  0.5848898 ]
 [-0.80178373  0.5848898   0.87733471]]
[[0.26726124 1.53452248 1.80178373]
 [1.53452248 0.61007346 0.4151102 ]
 [1.80178373 0.4151102  0.12266529]]
[[ 0.26726124  0.53452248  0.80178373]
 [ 0.53452248  0.61007346 -0.5848898 ]
 [ 0.80178373 -0.5848898   0.12266529]]
[ 3.74165739e+00  0.00000000e+00 -1.11022302e-16]


Протестируйте свою функцию на следующих примерах:

In [5]:
v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(h @ v1, v, atol=1e-14)
assert_allclose(h @ v, v1, atol=1e-14)

assert_allclose(v1[1:], 0, atol=1e-14)

assert_allclose(h @ h.T, np.eye(3), atol=1e-14)

###BEGIN HIDDEN TESTS
rndm = np.random.RandomState(1223)
vec = rndm.uniform(size=21)
v1, h = householder(vec)

assert_allclose(h @ v1, vec, atol=1e-14)
assert_allclose(h @ vec, v1, atol=1e-14)
assert_allclose(v1[1:], 0, atol=1e-14)

assert_allclose(h @ h.T, np.eye(h.shape[0]), atol=1e-14)
###END HIDDEN TESTS

### Part II. Вычисление $\mathrm{QR}$ - разложения матрицы.

Дана прямоугольная $m\times n$ матрица $\mathbf{A}$. Выполните отражение Хаусхолдера матрицы $\mathbf{H}_1$, преобразующее первый столбец матрицы $\mathbf{A}$ (назовем результат $\mathbf{A}^{(1)}$)

$$ 
\mathbf{H}_1 \mathbf{A} %\begin{pmatrix} \times &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ &amp;&amp; \dots&amp;&amp; \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ \end{pmatrix}
%
\equiv \mathbf{A}^{(1)}\;. 
$$

Теперь рассмотрим нижнюю правую часть матрицы $\mathbf{A}^{(1)}$ и выполним преобразование Хаусхолдера, действующее на 2 столбец $\mathbf{A}$:
$$
\mathbf{H}_2 \mathbf{A}^{(1)} % \begin{pmatrix} \times &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; 0 &amp; \times &amp; \dots &amp; \times \\ &amp;&amp; \dots&amp;&amp; \\ 0 &amp; 0 &amp; \times &amp; \dots &amp; \times \\ \end{pmatrix}
%
\equiv \mathbf{A}^{(2)} \;. $$

Повторяя процесс $n$ раз, получим
$$
\mathbf{H}_{n} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;, 
$$

где $\mathbf{R}$ верхняя треугольная матрица. Так как каждая из матриц $\mathbf{H}_k$ ортогональна, таковым будет и их произведение. Обратная от ортогональной также есть матрица ортогональная. Таким образом, алгоритм создает $\mathrm{QR}$ - разложение матрицы $\mathbf{A}$.

Напишите функцию, получающую прямоугольную матрицу $A$ и возвращающую матрицы $Q$ и $R$ --- компоненты $QR$-разложения $A$.


In [6]:
def qr_decomp(a):
    """Вычисляет QR - разложение матрицы.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        Введенная матрица
    
    Returns
    -------
    q : ndarray, shape(m, m)
        Ортогональная матрица
    r : ndarray, shape(m, n)
        Верхняя треугольная матрица
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_decomp(a)
    >>> np.testing.assert_allclose(q @ r, a, atol=1e-14)
    
    """
    a1 = np.array(a, copy=True, dtype=float)
    m, n = a1.shape
    count = min(m,n)
    QT = np.eye(m)
    Q = np.eye(m)
    for i in range(count):
      v, q = householder(a1[:,0])
      a1 = q @ a1
      qa = np.eye(m)
      qa[i:,i:] = q
      QT = qa @ QT
      Q = Q @ qa.T
      a1 = a1[1:,1:]

    R = QT @ a
    return Q, R

In [7]:
# можете запустить данную операцию для бооее сжатого вывода: нули вместо `1e-16` и т.д.
np.set_printoptions(suppress=True)

In [8]:
rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
aa = a.copy()

q, r = qr_decomp(a)

# check that `qr_decomp` leaves `a` intact
assert_allclose(a, aa, atol=1e-16)

# тестируем, что Q ортогональна
assert_allclose(q @ q.T, np.eye(5), atol=1e-14)

# проверяем разложение
assert_allclose(q @ r, a, atol=1e-14)

Теперь сравните ваше разложение с разложением, полученным библиотечной функцией (содержащей соответствующие функции библиотеки LAPACK)

In [9]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a,
                atol=1e-14)

Пояснений нет(


### Часть III. Безматричная реализация.

Отметим необычную структуру матрицы Хаусхолдера: матрица поворота $\mathbf{H}$ полностью характеризуется вектором отражения $\mathbf{u}$. Заметим, также, что вычислительная сложность операции отражения матрицы сильно зависит от порядка операций:
$$ \left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A} \qquad \textrm{is } O(m^2 n)\;, $$

тогда как $$ \mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn) $$

Таким образом, следует избегать формирований матриц $\mathbf{H}$. Вместо этого можно сохранять сами векторы отражения $\mathbf{u}$ и производить умножение произвольной матрицы на $\mathbf{Q}^T$, например, как отдельную функцию (класс).

Напишите функцию, выполняющую QR - разложение матрицы без формирования матриц $\mathbf{H}$ и возвращающую матрицу $\mathbf{R}$, а также вектора отражений Хаусхолдера.


Напишите вторую функцию, которая использует вектора отражений, полученных предыдущей функцией, для вычисления произведения $Q^T B$ для заданной матрицы B. Убедитесь, что вы добавили достаточно комментариев, следующих вашим выкладкам. 



In [10]:
def qr_nomatrix(a):
    """Form QR decomposition of `a` via successive Householder reflections.
    
    Parameters
    ----------
    a : ndarray
        Input matrix
    
    Returns
    -------
    R : ndarray
        Upper triangular matrix of the QR decomposition
    
    U : ndarray
        Columns store successive Householder reflectors: `U[j:, j]` stores
        the Householder reflector for reducing the `j`-th column.
        
    See Also
    --------
    householder_apply : apply Householder reflectors stored in `U` to `a`.
    
    """
    a1 = np.array(a, copy=True, dtype=float)
    m, n = a1.shape
    count = min(m,n)
    #print(m,n)

    QT = np.eye(m)
    Q = np.eye(m)
    U = np.eye(m)
    #print(U)

    for i in range(count):
      V = np.asarray(a1[:,0], dtype=float)
      if V.ndim != 1:
          raise ValueError("V.ndim = %s, expected 1" % V.ndim)
      if np.size(V)==1 and np.linalg.norm(V)<1e-8:
        q = [[1]]
        u = np.asarray([0])
      else:
        x = V
        y = np.zeros(np.size(V))
        y[0] = np.linalg.norm(V)
        u = (x - y) / np.linalg.norm(x - y)
        print("u", u)
      U[i:, i] = u
      print("U", U)
      q = np.eye(np.size(V))-2*(u[np.newaxis, :].T @ u[np.newaxis, :] )
      a1 = q @ a1
      qa = np.eye(m)
      qa[i:,i:] = q
      QT = qa @ QT
      Q = Q @ (qa.T)
      a1 = a1[1:,1:]
    R = QT @ a
    return R, U
  
def householder_apply(b, uu):
    """Apply the Householder reflectors stored in `uu` to `b`.
    
    The result is equivalent to
    >>> r, q = qr_decomp(a)
    >>> q.T @ b
    
    Parameters
    ----------
    b : ndarray
        Input matrix
    uu : ndarray
        Householder reflectors: `U[j:, j]` is the reflection vector
        for transforming the `j`-th column of `a`.
        
    Returns
    -------
    r : ndarray
        The result of applying the reflectors to `b`. Equivalent to
        computing `q.T @ b`.

    See Also
    --------
    qr_decomp
    
    """
    a1 = np.array(b, copy=True, dtype=float)
    m, n = a1.shape
    count = min(m,n)
    QT = np.eye(m)
    Q = np.eye(m)
    for i in range(count):
      u = U[i:, i]
      V = np.asarray(a1[:,0], dtype=float)
      q = np.eye(np.size(V))-2*(u[np.newaxis, :].T @ u[np.newaxis, :] )
      a1 = q @ a1
      qa = np.eye(m)
      qa[i:,i:] = q
      QT = qa @ QT
      Q = Q @ (qa.T)
      a1 = a1[1:,1:]
    R=QT@b
    return R

In [11]:
rndm = np.random.RandomState(1223)

a = rndm.uniform(size=(5, 5))
R1, U = qr_nomatrix(a)
R2 = householder_apply(a, U)
R_lib = qr(a)[1]
assert_allclose(R1, R2, atol=1e-14)

###BEGIN HIDDEN TESTS

name2 = "Test 2: vertical rectangular matrix"
a2 = rndm.uniform(size=(5, 3))
R1, U = qr_nomatrix(a2)
R22 = householder_apply(a2, U)
R_lib2 = qr(a2)[1]
assert_allclose(R1, R22, atol=1e-14)


name3 = "Test 3: horizontal rectangular matrix"
a3 = rndm.uniform(size=(3, 5))
R1, U = qr_nomatrix(a3)
R23 = householder_apply(a3, U)
R_lib3 = qr(a3)[1]
assert_allclose(R1, R23, atol=1e-14)

###END HIDDEN TESTS

u [-0.51706743  0.1189934   0.38529641  0.72128983  0.22309079]
U [[-0.51706743  0.          0.          0.          0.        ]
 [ 0.1189934   1.          0.          0.          0.        ]
 [ 0.38529641  0.          1.          0.          0.        ]
 [ 0.72128983  0.          0.          1.          0.        ]
 [ 0.22309079  0.          0.          0.          1.        ]]
u [-0.71706866 -0.16784218 -0.19207851  0.64865043]
U [[-0.51706743  0.          0.          0.          0.        ]
 [ 0.1189934  -0.71706866  0.          0.          0.        ]
 [ 0.38529641 -0.16784218  1.          0.          0.        ]
 [ 0.72128983 -0.19207851  0.          1.          0.        ]
 [ 0.22309079  0.64865043  0.          0.          1.        ]]
u [-0.66214187 -0.2285334   0.71368104]
U [[-0.51706743  0.          0.          0.          0.        ]
 [ 0.1189934  -0.71706866  0.          0.          0.        ]
 [ 0.38529641 -0.16784218 -0.66214187  0.          0.        ]
 [ 0.72128983 -0.

In [12]:
# Check consistency with the scipy library decomposition. Allow for sign differences

conds = [np.allclose(R2[i, :], R_lib[i, :], atol=1e-14) or
         np.allclose(R2[i, :], -R_lib[i, :], atol=1e-14) for i in range(5)]
assert False not in conds

###BEGIN HIDDEN TESTS
conds = [np.allclose(R22[i, :], R_lib2[i, :], atol=1e-14) or
         np.allclose(R22[i, :], -R_lib2[i, :], atol=1e-14) for i in range(5)]
assert False not in conds

conds = [np.allclose(R23[i, :], R_lib3[i, :], atol=1e-14) or
         np.allclose(R23[i, :], -R_lib3[i, :], atol=1e-14) for i in range(3)]
assert False not in conds
###END HIDDEN TESTS

In [13]:
# More testing here, keep this cell intact

### BEGIN HIDDEN TESTS

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))

q, r = qr_decomp(a)
rr, uu = qr_nomatrix(a)

# check consistency
assert_allclose(np.triu(r),
                np.triu(rr), atol=1e-14)

# $Q^T @ A = R$
assert_allclose(householder_apply(a, uu),
                r,
                atol=1e-14)

# act on a different matrix
b = rndm.uniform(size=(5, 3))
assert_allclose(householder_apply(b, uu),
                q.T @ b,
                atol=1e-14)

# END HIDDEN TESTS

u [-0.6570196   0.42644006  0.15011669  0.47562065  0.37111197]
U [[-0.6570196   0.          0.          0.          0.        ]
 [ 0.42644006  1.          0.          0.          0.        ]
 [ 0.15011669  0.          1.          0.          0.        ]
 [ 0.47562065  0.          0.          1.          0.        ]
 [ 0.37111197  0.          0.          0.          1.        ]]
u [-0.52846942  0.73983285 -0.10990213  0.40160796]
U [[-0.6570196   0.          0.          0.          0.        ]
 [ 0.42644006 -0.52846942  0.          0.          0.        ]
 [ 0.15011669  0.73983285  1.          0.          0.        ]
 [ 0.47562065 -0.10990213  0.          1.          0.        ]
 [ 0.37111197  0.40160796  0.          0.          1.        ]]
u [-0.79133207  0.36468006 -0.49071581]
U [[-0.6570196   0.          0.          0.          0.        ]
 [ 0.42644006 -0.52846942  0.          0.          0.        ]
 [ 0.15011669  0.73983285 -0.79133207  0.          0.        ]
 [ 0.47562065 -0.

ValueError: operands could not be broadcast together with shapes (5,5) (3,3) 