Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [1]:
NAME = "espetukhova"
COLLABORATORS = ""

---

In [2]:
import numpy as np

from numpy.testing import assert_allclose


### Часть I. Постройте отражение Хаусхолдера для вектора.

Дан вектор $\mathbf{x}$ и плоскость, заданная вектором нормали $\mathbf{u}$. Преобразование Хаусхолдера отражает $\mathbf{x}$ относительно плоскости.

Матрица преобразований Хаусхолдера:
$$ \mathbf{H} = \mathbf{1} - 2 \mathbf{u} \mathbf{u}^T $$

Если даны два вектора $\mathbf{x}$ и $\mathbf{y}$ одинаковой длины, поворот, преобразующий $\mathbf{x}$ в $\mathbf{y}$ называется преобразованием Хаусхолдера с
$$ \mathbf{u} = \frac{\mathbf{x} - \mathbf{y}}{\left|\mathbf{x} - \mathbf{y}\right|} $$

Напишите функцию, преобразующую заданный вектор $\mathbf{x} = (x_1, \dots, x_n)$ в $\mathbf{y} = (\left|\mathbf{x}\right|, 0, \dots, 0)^T$, используя преобразование Хаусхолдера.


In [3]:
import numpy as np
def householder(vec):
    """Создает отражение Хаусхолдера, преобразующее 2-ю, 3-ю и т.д. компоненты вектора vec в нули.
    
    Parameters
    ----------
    vec : array-like of floats, shape (n,)
        Введенный вектор
    
    Returns
    -------
    outvec : array of floats, shape (n,)
        Преобразованный вектор, причем ``outvec[1:]==0`` и ``|outvec| == |vec|``
    H : array of floats, shape (n, n)
        Ортогональная матрица отражений Хаусхолдера
    """
    vec = np.asarray(vec, dtype=float)
    if vec.ndim != 1:
        raise ValueError("vec.ndim = %s, expected 1" % vec.ndim)
    
    # YOUR CODE HERE
    n = len(vec)
    I = np.eye(n)
    e1 = np.zeros_like(vec).astype(float)
    e1[0] = 1.0
    V1 = e1 * np.linalg.norm(vec)# вектор у
    print("V1:", V1)
    u = vec.copy()
    u[0] = vec[0] - np.linalg.norm(vec)
    u = u / np.linalg.norm(u)
    H = I - 2 * (np.outer(u, np.transpose(u)))
    print("H:", H)
    return V1 , H
   

Протестируйте свою функцию на следующих примерах:

In [4]:
v = np.array([1, 2, 3])
v1, h = householder(v)

assert_allclose(h @ v1, v, atol=1e-14)
assert_allclose(h @ v, v1, atol=1e-14)

assert_allclose(v1[1:], 0, atol=1e-14)

assert_allclose(h @ h.T, np.eye(3), atol=1e-14)

###BEGIN HIDDEN TESTS
rndm = np.random.RandomState(1223)
vec = rndm.uniform(size=21)
v1, h = householder(vec)

assert_allclose(h @ v1, vec, atol=1e-14)
assert_allclose(h @ vec, v1, atol=1e-14)
assert_allclose(v1[1:], 0, atol=1e-14)

assert_allclose(h @ h.T, np.eye(h.shape[0]), atol=1e-14)
###END HIDDEN TESTS

V1: [3.74165739 0.         0.        ]
H: [[ 0.26726124  0.53452248  0.80178373]
 [ 0.53452248  0.61007346 -0.5848898 ]
 [ 0.80178373 -0.5848898   0.12266529]]
V1: [2.82373829 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.        ]
H: [[ 1.87367505e-01  5.78503909e-02  3.51216331e-01  9.12162209e-03
   2.28514252e-01  4.95538703e-02  1.75455381e-02  3.50197494e-01
   8.94415846e-02  3.05557705e-01  1.60453676e-01  3.62678714e-02
   2.91351470e-01  2.56165134e-01  1.22644622e-01  3.00375504e-01
   9.20715413e-02  3.24421782e-01  3.52166885e-01  1.72948831e-01
   9.29044118e-02]
 [ 5.78503909e-02  9.95881696e-01 -2.50026946e-02 -6.49357990e-04
  -1.62676719e-02 -3.52768414e-03 -1.24904707e-03 -2.49301647e-02
  -6.36724554e-03 -2.17523084e-02 -1.14225162e-02 -2.58186886e-03
  -2.07409826e-02 -1.82361070e-02 -8.73093232e-03 -2.13833934e-02
  -6.554

### Part II. Вычисление $\mathrm{QR}$ - разложения матрицы.

Дана прямоугольная $m\times n$ матрица $\mathbf{A}$. Выполните отражение Хаусхолдера матрицы $\mathbf{H}_1$, преобразующее первый столбец матрицы $\mathbf{A}$ (назовем результат $\mathbf{A}^{(1)}$)

$$ 
\mathbf{H}_1 \mathbf{A} %\begin{pmatrix} \times &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ &amp;&amp; \dots&amp;&amp; \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ \end{pmatrix}
%
\equiv \mathbf{A}^{(1)}\;. 
$$

Теперь рассмотрим нижнюю правую часть матрицы $\mathbf{A}^{(1)}$ и выполним преобразование Хаусхолдера, действующее на 2 столбец $\mathbf{A}$:
$$
\mathbf{H}_2 \mathbf{A}^{(1)} % \begin{pmatrix} \times &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; \times &amp; \times &amp; \dots &amp; \times \\ 0 &amp; 0 &amp; \times &amp; \dots &amp; \times \\ &amp;&amp; \dots&amp;&amp; \\ 0 &amp; 0 &amp; \times &amp; \dots &amp; \times \\ \end{pmatrix}
%
\equiv \mathbf{A}^{(2)} \;. $$

Повторяя процесс $n$ раз, получим
$$
\mathbf{H}_{n} \cdots \mathbf{H}_2 \mathbf{H}_1 \mathbf{A} = \mathbf{R} \;, 
$$

где $\mathbf{R}$ верхняя треугольная матрица. Так как каждая из матриц $\mathbf{H}_k$ ортогональна, таковым будет и их произведение. Обратная от ортогональной также есть матрица ортогональная. Таким образом, алгоритм создает $\mathrm{QR}$ - разложение матрицы $\mathbf{A}$.

Напишите функцию, получающую прямоугольную матрицу $A$ и возвращающую матрицы $Q$ и $R$ --- компоненты $QR$-разложения $A$.


In [5]:
def qr_decomp(a):
    """Вычисляет QR - разложение матрицы.
    
    Parameters
    ----------
    a : ndarray, shape(m, n)
        Введенная матрица
    
    Returns
    -------
    q : ndarray, shape(m, m)
        Ортогональная матрица
    r : ndarray, shape(m, n)
        Верхняя треугольная матрица
        
    Examples
    --------
    >>> a = np.random.random(size=(3, 5))
    >>> q, r = qr_decomp(a)
    >>> np.testing.assert_allclose(q @ r, a, atol=1e-14)
    
    """
    a1 = np.array(a, copy=True, dtype=float)
    m, n = a1.shape
    
    # YOUR CODE HERE
    R = a1.copy()
    Q = np.identity(m)

    for j in range(0, n):
        # Apply Householder transformation.
        h = np.eye(m)
        V1, H = householder(R[j:,j])
        h[j:, j:] = H
        R = h @ R
        Q = Q @ h

    return Q,R

In [6]:
# можете запустить данную операцию для бооее сжатого вывода: нули вместо `1e-16` и т.д.
np.set_printoptions(suppress=True)

In [7]:
rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))
aa = a.copy()

q, r = qr_decomp(a)

# check that `qr_decomp` leaves `a` intact
assert_allclose(a, aa, atol=1e-16)

# тестируем, что Q ортогональна
assert_allclose(q @ q.T, np.eye(5), atol=1e-14)

# проверяем разложение
assert_allclose(q @ r, a, atol=1e-14)

V1: [1.40152769 0.         0.         0.         0.        ]
H: [[ 0.13665049  0.56035895  0.19725922  0.62498418  0.48765568]
 [ 0.56035895  0.63629775 -0.12803154 -0.4056474  -0.31651402]
 [ 0.19725922 -0.12803154  0.95492996 -0.1427972  -0.1114202 ]
 [ 0.62498418 -0.4056474  -0.1427972   0.54756999 -0.35301704]
 [ 0.48765568 -0.31651402 -0.1114202  -0.35301704  0.72455181]]
V1: [0.84158252 0.         0.         0.        ]
H: [[ 0.44144015  0.78195807 -0.11615982  0.42447505]
 [ 0.78195807 -0.09470529  0.1626184  -0.59424552]
 [-0.11615982  0.1626184   0.97584305  0.08827514]
 [ 0.42447505 -0.59424552  0.08827514  0.67742209]]
V1: [0.5496046 0.        0.       ]
H: [[-0.25241289  0.57716606 -0.77663832]
 [ 0.57716606  0.7340169   0.35790855]
 [-0.77663832  0.35790855  0.51839599]]


Теперь сравните ваше разложение с разложением, полученным библиотечной функцией (содержащей соответствующие функции библиотеки LAPACK)

In [8]:
from scipy.linalg import qr
qq, rr = qr(a)

assert_allclose(np.dot(qq, rr), a,
                atol=1e-14)

Проверьте, согласуются ли ваши матрицы `q` и `r` с `qq` и `rr`. Объясните результат.
Оставьте пояснения в этой ячейке.

In [9]:
print('Q:\n', q, '\n')
print('QQ:\n', qq, '\n')
print('R:\n', r, '\n')
print('RR:\n', rr)

Q:
 [[ 0.13665049  0.53601299 -0.09369752  0.7697136   0.30459557]
 [ 0.56035895  0.0935397  -0.53326881  0.01839528 -0.62652547]
 [ 0.19725922  0.65948912  0.60068463 -0.32384673 -0.24589462]
 [ 0.62498418 -0.50418303  0.52144688  0.28453698  0.04822969]
 [ 0.48765568  0.12171264 -0.27224305 -0.47049398  0.67223293]] 

QQ:
 [[-0.13665049  0.53601299  0.09369752  0.661619   -0.49749149]
 [-0.56035895  0.0935397   0.53326881 -0.52477245 -0.34276292]
 [-0.19725922  0.65948912 -0.60068463 -0.37879015  0.14784752]
 [-0.62498418 -0.50418303 -0.52144688  0.18967657 -0.21750907]
 [-0.48765568  0.12171264  0.27224305  0.32774225  0.75222783]] 

R:
 [[ 1.40152769  1.2514379   0.89523615]
 [ 0.          0.84158252  0.68447942]
 [-0.          0.          0.5496046 ]
 [ 0.         -0.         -0.        ]
 [ 0.          0.          0.        ]] 

RR:
 [[-1.40152769 -1.2514379  -0.89523615]
 [ 0.          0.84158252  0.68447942]
 [ 0.          0.         -0.5496046 ]
 [ 0.          0.          0.  


### Часть III. Безматричная реализация.

Отметим необычную структуру матрицы Хаусхолдера: матрица поворота $\mathbf{H}$ полностью характеризуется вектором отражения $\mathbf{u}$. Заметим, также, что вычислительная сложность операции отражения матрицы сильно зависит от порядка операций:
$$ \left( \mathbf{u} \mathbf{u}^T \right) \mathbf{A} \qquad \textrm{is } O(m^2 n)\;, $$

тогда как $$ \mathbf{u} \left( \mathbf{u}^T \mathbf{A} \right) \qquad \textrm{is } O(mn) $$

Таким образом, следует избегать формирований матриц $\mathbf{H}$. Вместо этого можно сохранять сами векторы отражения $\mathbf{u}$ и производить умножение произвольной матрицы на $\mathbf{Q}^T$, например, как отдельную функцию (класс).

Напишите функцию, выполняющую QR - разложение матрицы без формирования матриц $\mathbf{H}$ и возвращающую матрицу $\mathbf{R}$, а также вектора отражений Хаусхолдера.


Напишите вторую функцию, которая использует вектора отражений, полученных предыдущей функцией, для вычисления произведения $Q^T B$ для заданной матрицы B. Убедитесь, что вы добавили достаточно комментариев, следующих вашим выкладкам. 



In [10]:
def norm(v):
    return np.sqrt(np.sum(v**2))

In [11]:
def qr_nomatrix(a):
    """Form QR decomposition of `a` via successive Householder reflections.
    
    Parameters
    ----------
    a : ndarray
        Input matrix
    
    Returns
    -------
    R : ndarray
        Upper triangular matrix of the QR decomposition
    
    U : ndarray
        Columns store successive Householder reflectors: `U[j:, j]` stores
        the Householder reflector for reducing the `j`-th column.
        
    See Also
    --------
    householder_apply : apply Householder reflectors stored in `U` to `a`.
    
    """
    # YOUR CODE HERE
    a2 = np.array(a, copy=True, dtype=float)
    m, n = a2.shape
    U = np.zeros((m,n))
    for i in range(n):
        x = a2[i:, i]
        y = np.zeros_like(x)
        y[0] = norm(x)
        if x[0] > 0:
            d = x.copy()
            d[0] = -np.sum(x[1:]**2) / (x[0] + norm(x))
            u = d / norm(d)
        else:
            u = (x - y) / norm(x-y)
        u = np.reshape(u, (1, x.shape[0]))
        for k in range(m - i):
            U[i:,i] = u
        u_ = np.reshape(U[:, i], (1, m))
        a2 = a2 - 2* u_.T @ (u_ @ a2)
    return a2, U

    
def householder_apply(b, uu):
    """Apply the Householder reflectors stored in `uu` to `b`.
    
    The result is equivalent to
    >>> r, q = qr_decomp(a)
    >>> q.T @ b
    
    Parameters
    ----------
    b : ndarray
        Input matrix
    uu : ndarray
        Householder reflectors: `U[j:, j]` is the reflection vector
        for transforming the `j`-th column of `a`.
        
    Returns
    -------
    r : ndarray
        The result of applying the reflectors to `b`. Equivalent to
        computing `q.T @ b`.

    See Also
    --------
    qr_decomp
    
    """
    b1 = np.array(b, copy=True, dtype=float)
    for i in range(uu.shape[1]):
        u = np.reshape(uu[:, i], (1, uu.shape[0]))
        b1 = b1 - 2* u.T @ (u @ b1)
    return b1

In [12]:
rndm = np.random.RandomState(1223)

a = rndm.uniform(size=(5, 5))
R1, U = qr_nomatrix(a)
R2 = householder_apply(a, U)
R_lib = qr(a)[1]
assert_allclose(R1, R2, atol=1e-14)

###BEGIN HIDDEN TESTS

name2 = "Test 2: vertical rectangular matrix"
a2 = rndm.uniform(size=(5, 3))
R1, U = qr_nomatrix(a2)
R22 = householder_apply(a2, U)
R_lib2 = qr(a2)[1]
assert_allclose(R1, R22, atol=1e-14)


name3 = "Test 3: horizontal rectangular matrix"
a3 = rndm.uniform(size=(3, 5))
R1, U = qr_nomatrix(a3)
R23 = householder_apply(a3, U)
R_lib3 = qr(a3)[1]
assert_allclose(R1, R23, atol=1e-14)

###END HIDDEN TESTS

IndexError: index 0 is out of bounds for axis 0 with size 0

In [13]:
# Check consistency with the scipy library decomposition. Allow for sign differences

conds = [np.allclose(R2[i, :], R_lib[i, :], atol=1e-14) or
         np.allclose(R2[i, :], -R_lib[i, :], atol=1e-14) for i in range(5)]
assert False not in conds

###BEGIN HIDDEN TESTS
conds = [np.allclose(R22[i, :], R_lib2[i, :], atol=1e-14) or
         np.allclose(R22[i, :], -R_lib2[i, :], atol=1e-14) for i in range(5)]
assert False not in conds

conds = [np.allclose(R23[i, :], R_lib3[i, :], atol=1e-14) or
         np.allclose(R23[i, :], -R_lib3[i, :], atol=1e-14) for i in range(3)]
assert False not in conds
###END HIDDEN TESTS

NameError: name 'R23' is not defined

In [14]:
# More testing here, keep this cell intact

### BEGIN HIDDEN TESTS

rndm = np.random.RandomState(1234)
a = rndm.uniform(size=(5, 3))

q, r = qr_decomp(a)
rr, uu = qr_nomatrix(a)

# check consistency
assert_allclose(np.triu(r),
                np.triu(rr), atol=1e-14)

# $Q^T @ A = R$
assert_allclose(householder_apply(a, uu),
                r,
                atol=1e-14)

# act on a different matrix
b = rndm.uniform(size=(5, 3))
assert_allclose(householder_apply(b, uu),
                q.T @ b,
                atol=1e-14)

# END HIDDEN TESTS

V1: [1.40152769 0.         0.         0.         0.        ]
H: [[ 0.13665049  0.56035895  0.19725922  0.62498418  0.48765568]
 [ 0.56035895  0.63629775 -0.12803154 -0.4056474  -0.31651402]
 [ 0.19725922 -0.12803154  0.95492996 -0.1427972  -0.1114202 ]
 [ 0.62498418 -0.4056474  -0.1427972   0.54756999 -0.35301704]
 [ 0.48765568 -0.31651402 -0.1114202  -0.35301704  0.72455181]]
V1: [0.84158252 0.         0.         0.        ]
H: [[ 0.44144015  0.78195807 -0.11615982  0.42447505]
 [ 0.78195807 -0.09470529  0.1626184  -0.59424552]
 [-0.11615982  0.1626184   0.97584305  0.08827514]
 [ 0.42447505 -0.59424552  0.08827514  0.67742209]]
V1: [0.5496046 0.        0.       ]
H: [[-0.25241289  0.57716606 -0.77663832]
 [ 0.57716606  0.7340169   0.35790855]
 [-0.77663832  0.35790855  0.51839599]]
